[package]
name = "riddle-lsp"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
ast = { path = "../../crates/ast" }
clap = { version = "=4.5.61", features = ["derive", "string", "env"] }
clue = { path = "../clue" }
frontend = { path = "../../crates/frontend" }
hir = { path = "../../crates/hir" }
lsp-types = "0.94.1"
riddlec = { path = "../riddlec" }
rowan = "0.16.1"
scope-graph = { path = "../../crates/scope-graph" }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syntax = { path = "../../crates/syntax" }
tokio = { version = "1", features = ["io-std", "macros", "rt-multi-thread", "sync", "time"] }
toml_edit = "0.24"
tower-lsp = "0.20.0"
type-checker = { path = "../../crates/type-checker" }

[features]
test = []
