use std::collections::{HashMap, HashSet};
use std::fmt::Write;
use std::hash::{DefaultHasher, Hash, Hasher};

use crate::backend::Backend;
use crate::func::Function;
use crate::instr::{BinOp, CastOp, CmpOp, ConstValue, Inst, InstKind, Terminator, UnOp};
use crate::module::Module;
use crate::types::{FloatTy, FnPtrType, IntTy, StructType, Type};
use crate::value::{FuncRef, Value};

#[derive(Debug, Default)]
pub struct CBackend {
    names: Vec<String>,
    counter: u64,
    ctypes: Vec<String>,
    /// Value -> `StructType` mapping for field name lookup in `ExtractValue`.
    struct_types: HashMap<u32, StructType>,
    /// Count of how many times each value is referenced as an operand.
    use_counts: HashMap<u32, u32>,
    /// Expression text for values inlined at use sites (no variable emitted).
    inline_of: HashMap<u32, String>,
    /// Alloca values name their C storage directly, even when that storage holds a pointer.
    direct_storage: HashSet<u32>,
    c_exports: HashSet<String>,
    needs_runtime: bool,
    no_gc: bool,
}

impl CBackend {
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    #[must_use]
    pub fn without_gc() -> Self {
        Self {
            no_gc: true,
            ..Self::default()
        }
    }

    fn ensure(&mut self, v: Value) {
        let idx = v.0 as usize;
        if idx >= self.names.len() {
            self.names.resize(idx + 1, String::new());
            self.ctypes.resize(idx + 1, String::new());
        }
    }

    fn set(&mut self, v: Value, name: String, ctype: String) {
        self.ensure(v);
        self.names[v.0 as usize] = name;
        self.ctypes[v.0 as usize] = ctype;
    }

    fn name(&self, v: Value) -> &str {
        if let Some(expr) = self.inline_of.get(&v.0) {
            if expr.is_empty() {
                return "0";
            }
            return expr.as_str();
        }
        self.names
            .get(v.0 as usize)
            .map(std::string::String::as_str)
            .filter(|s| !s.is_empty())
            .unwrap_or("0")
    }

    fn value_expr(&self, v: Value) -> String {
        if self.direct_storage.contains(&v.0) {
            format!("(&{})", self.name(v))
        } else {
            self.name(v).to_owned()
        }
    }

    fn set_inline(&mut self, v: Value, expr: String, ctype: String) {
        self.ensure(v);
        self.inline_of.insert(v.0, expr);
        self.ctypes[v.0 as usize] = ctype;
    }

    fn is_indirect(&self, v: Value) -> bool {
        if self.direct_storage.contains(&v.0) {
            return false;
        }
        self.ctypes
            .get(v.0 as usize)
            .is_some_and(|ct| ct.ends_with('*'))
    }

    fn record_struct_type(&mut self, v: Value, ty: &Type) {
        if let Some(st) = struct_type_for_field_base(ty) {
            self.struct_types.insert(v.0, st);
        }
    }
}

impl Backend for CBackend {
    type Error = String;

    fn compile(&mut self, module: &Module) -> Result<String, Self::Error> {
        let mut out = String::new();
        self.emit_module_prelude(module, &mut out);
        Self::emit_type_declarations(module, &mut out);
        self.emit_function_declarations(module, &mut out)?;
        for &fid in &module.function_order {
            self.compile_function(&module.functions[fid], &mut out)?;
            writeln!(out).unwrap();
        }
        self.emit_runtime_main(module, &mut out)?;
        Ok(out)
    }

    fn name(&self) -> &'static str {
        "c"
    }
}

impl CBackend {
    fn emit_module_prelude(&mut self, module: &Module, out: &mut String) {
        self.c_exports = module
            .functions
            .values()
            .filter(|function| function.is_c_export)
            .map(|function| function.name.clone())
            .collect();
        self.needs_runtime = module_has_heap_alloc(module) || module_calls_runtime(module);

        writeln!(out, "// Generated by Riddle").unwrap();
        if self.needs_runtime {
            writeln!(out, "// Compile: cc out.c runtime.c -o out").unwrap();
        } else {
            writeln!(out, "// Compile: cc out.c -o out").unwrap();
        }
        writeln!(out).unwrap();
        writeln!(out, "#include <stddef.h>").unwrap();
        writeln!(out, "#include <stdint.h>").unwrap();
        writeln!(out, "#include <stdbool.h>").unwrap();
        writeln!(out, "#include <stdio.h>").unwrap();
        writeln!(out, "#include <stdlib.h>").unwrap();
        writeln!(out, "#include <string.h>").unwrap();
        writeln!(out, "#include <limits.h>").unwrap();
        writeln!(out, "#include <math.h>").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#define RIDDLE_I8_FROM_BITS(v) (((uint32_t)(v) & UINT32_C(0xff)) <= (uint32_t)INT8_MAX ? (int8_t)((uint32_t)(v) & UINT32_C(0xff)) : (int8_t)(-1 - (int8_t)(UINT32_C(0xff) - ((uint32_t)(v) & UINT32_C(0xff)))))").unwrap();
        writeln!(out, "#define RIDDLE_I16_FROM_BITS(v) (((uint32_t)(v) & UINT32_C(0xffff)) <= (uint32_t)INT16_MAX ? (int16_t)((uint32_t)(v) & UINT32_C(0xffff)) : (int16_t)(-1 - (int16_t)(UINT32_C(0xffff) - ((uint32_t)(v) & UINT32_C(0xffff)))))").unwrap();
        writeln!(out, "#define RIDDLE_I32_FROM_BITS(v) ((uint32_t)(v) <= (uint32_t)INT32_MAX ? (int32_t)(uint32_t)(v) : (int32_t)(-1 - (int32_t)(UINT32_MAX - (uint32_t)(v))))").unwrap();
        writeln!(out, "#define RIDDLE_I64_FROM_BITS(v) ((uint64_t)(v) <= (uint64_t)INT64_MAX ? (int64_t)(uint64_t)(v) : (int64_t)(-1 - (int64_t)(UINT64_MAX - (uint64_t)(v))))").unwrap();
        writeln!(out, "#define RIDDLE_ISIZE_FROM_BITS(v) ((uintptr_t)(v) <= (uintptr_t)PTRDIFF_MAX ? (ptrdiff_t)(uintptr_t)(v) : (ptrdiff_t)(-1 - (ptrdiff_t)(UINTPTR_MAX - (uintptr_t)(v))))").unwrap();
        writeln!(out).unwrap();
        if self.needs_runtime {
            if self.no_gc {
                writeln!(out, "void *riddle_alloc(size_t size);").unwrap();
                writeln!(out, "void *riddle_realloc(void *ptr, size_t size);").unwrap();
                writeln!(out, "void riddle_free(void *ptr);").unwrap();
            } else {
                writeln!(out, "void rgc_init(void *stack_bottom);").unwrap();
                writeln!(out, "void *rgc_alloc(size_t size);").unwrap();
                writeln!(out, "void rgc_free(void *ptr);").unwrap();
                writeln!(out, "void rgc_collect(void);").unwrap();
            }
            writeln!(out).unwrap();
        }

        writeln!(
            out,
            "typedef struct {{ const char* ptr; size_t len; }} riddle_str;"
        )
        .unwrap();
        writeln!(
            out,
            "typedef struct {{ void* ptr; size_t len; }} riddle_slice;"
        )
        .unwrap();
        // ponytail: C needs an addressable unit token until generic ZST storage is supported.
        writeln!(out, "typedef unsigned char riddle_unit;").unwrap();
        writeln!(out).unwrap();
    }

    fn emit_type_declarations(module: &Module, out: &mut String) {
        let structs = collect_structs(module);
        for strukt in &structs {
            let name = c_type_name(&strukt.name);
            writeln!(out, "typedef struct {name} {name};").unwrap();
        }
        if !structs.is_empty() {
            writeln!(out).unwrap();
        }

        for signature in collect_fn_ptrs(module) {
            let params = signature
                .params
                .iter()
                .enumerate()
                .map(|(index, ty)| c_param_decl(ty, &format!("p{index}")))
                .collect::<Vec<_>>();
            writeln!(
                out,
                "typedef {} (*{})({});",
                c_callable_return_type(&signature.ret),
                fn_ptr_name(&signature),
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        for s in &structs {
            writeln!(out, "struct {} {{", c_type_name(&s.name)).unwrap();
            if s.fields.is_empty() {
                writeln!(out, "  unsigned char _riddle_zst;").unwrap();
            }
            for (name, ty) in &s.fields {
                if matches!(ty, Type::Unit | Type::Never | Type::Void) {
                    writeln!(out, "  unsigned char {};", c_source_name('m', name)).unwrap();
                    continue;
                }
                let (pre, suf) = c_decl_parts(ty);
                writeln!(out, "  {} {}{};", pre, c_source_name('m', name), suf).unwrap();
            }
            writeln!(out, "}};").unwrap();
            writeln!(out).unwrap();
        }
    }

    fn emit_function_declarations(&self, module: &Module, out: &mut String) -> Result<(), String> {
        // Forward declarations
        for &fid in &module.function_order {
            let func = &module.functions[fid];
            let ret = c_return_type(func);
            let params: Vec<String> = func
                .params
                .iter()
                .enumerate()
                .map(|(index, p)| c_function_param_decl(func, &p.ty, &format!("p{index}")))
                .collect();
            let sname = self.c_function_name(&func.name)?;
            writeln!(
                out,
                "{} {}({});",
                ret,
                sname,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }

        // Extern function declarations
        for ext in &module.externs {
            if ext.params.iter().any(is_slice_ref) || is_slice_ref(&ext.ret_type) {
                return Err(format!(
                    "C extern function `{}` cannot use a slice; pass a pointer and length separately",
                    ext.name
                ));
            }
            if ext.params.iter().any(|ty| matches!(ty, Type::Str)) {
                return Err(format!(
                    "C extern function `{}` cannot take unsized `str`; use `&str`",
                    ext.name
                ));
            }
            if matches!(ext.ret_type, Type::Str) {
                return Err(format!(
                    "C extern function `{}` cannot return unsized `str`; use `&str`",
                    ext.name
                ));
            }
            let extern_name = self.extern_name(&ext.name)?;
            if !is_valid_c_extern_name(extern_name) {
                return Err(format!(
                    "C extern function `{}` is not a valid C identifier",
                    ext.name
                ));
            }
            // Expand &str parameters into (const char*, size_t) pairs so the
            // C function receives both the pointer and the length.
            let params: Vec<String> = ext
                .params
                .iter()
                .flat_map(|ty| {
                    if is_str_ref(ty) {
                        vec!["const char*".into(), "size_t".into()]
                    } else {
                        vec![ctype_of_ffi(ty)]
                    }
                })
                .collect();
            writeln!(
                out,
                "extern {} {}({});",
                c_ffi_return_type(&ext.ret_type),
                extern_name,
                if params.is_empty() {
                    "void".into()
                } else {
                    params.join(", ")
                }
            )
            .unwrap();
        }
        writeln!(out).unwrap();
        Ok(())
    }

    fn emit_runtime_main(&self, module: &Module, out: &mut String) -> Result<(), String> {
        if self.needs_runtime
            && let Some(main) = module
                .function_order
                .iter()
                .map(|fid| &module.functions[*fid])
                .find(|function| function.name == "main")
        {
            if !main.params.is_empty() {
                return Err("runtime-backed `main` cannot take parameters".into());
            }
            let user_main = self.c_function_name("main")?;
            writeln!(out, "int main(void) {{").unwrap();
            if !self.no_gc {
                writeln!(out, "  int rgc_stack_anchor = 0;").unwrap();
                writeln!(out, "  rgc_init(&rgc_stack_anchor);").unwrap();
            }
            writeln!(out, "  return (int){user_main}();").unwrap();
            writeln!(out, "}}").unwrap();
        }
        Ok(())
    }

    fn extern_name<'a>(&self, name: &'a str) -> Result<&'a str, String> {
        if !self.no_gc {
            return Ok(name);
        }
        match name {
            "rgc_alloc" => Ok("riddle_alloc"),
            "rgc_realloc" => Ok("riddle_realloc"),
            "rgc_free" => Ok("riddle_free"),
            name if name.starts_with("rgc_") => Err(format!(
                "GC is disabled; runtime symbol `{name}` is unavailable"
            )),
            _ => Ok(name),
        }
    }

    fn compile_function(&mut self, func: &Function, out: &mut String) -> Result<(), String> {
        self.names.clear();
        self.ctypes.clear();
        self.struct_types.clear();
        self.inline_of.clear();
        self.direct_storage.clear();
        self.counter = 0;
        self.use_counts = count_uses(func);

        let mut exported_strings = Vec::new();
        for p in &func.params {
            let ct = ctype_of(&p.ty);
            let abi_name = c_source_name('v', &p.name);
            if func.uses_c_string_abi
                && matches!(&p.ty, Type::Ref(inner, _) if **inner == Type::Str)
            {
                let internal_name = fresh_c(&mut self.counter, "export_str");
                self.set(p.value, internal_name.clone(), ct);
                exported_strings.push((abi_name, internal_name));
            } else {
                self.set(p.value, abi_name, ct);
            }
            self.record_struct_type(p.value, &p.ty);
        }

        let ret_ct = c_return_type(func);
        let param_strs: Vec<String> = func
            .params
            .iter()
            .map(|p| c_function_param_decl(func, &p.ty, &c_source_name('v', &p.name)))
            .collect();

        let sname = self.c_function_name(&func.name)?;
        write!(out, "{ret_ct} {sname} (").unwrap();
        if param_strs.is_empty() {
            write!(out, "void").unwrap();
        } else {
            for (i, p) in param_strs.iter().enumerate() {
                if i > 0 {
                    write!(out, ", ").unwrap();
                }
                write!(out, "{p}").unwrap();
            }
        }
        writeln!(out, ") {{").unwrap();

        for (abi_name, internal_name) in exported_strings {
            writeln!(
                out,
                "  riddle_str {internal_name} = (riddle_str){{ {abi_name}, {abi_name} ? strlen({abi_name}) : 0 }};"
            )
            .unwrap();
        }

        self.predeclare_phi_vars(func, out);

        for (bid, block) in func.blocks.iter() {
            let bid_raw = bid.into_raw();
            if let Some(ref label) = block.label {
                writeln!(out, "block_{label}_{bid_raw}:;").unwrap();
            }

            for (i, inst) in block.insts.iter().enumerate() {
                let v = block.value_at(i);
                self.emit_inst(inst, v, out)?;
            }

            self.emit_terminator(func, bid, &block.terminator, out)?;
        }

        writeln!(out, "}}").unwrap();
        Ok(())
    }

    fn emit_terminator(
        &self,
        func: &Function,
        block: crate::value::BlockId,
        terminator: &Terminator,
        out: &mut String,
    ) -> Result<(), String> {
        match terminator {
            Terminator::Pending => {
                return Err(format!("block {} has no terminator", block.into_raw()));
            }
            Terminator::Return(value) => {
                if func.name == "main" && matches!(func.ret_type, Type::Unit) {
                    writeln!(out, "  return 0;").unwrap();
                } else if matches!(func.ret_type, Type::Unit | Type::Never | Type::Void) {
                    writeln!(out, "  return;").unwrap();
                } else if let Some(value) = value {
                    writeln!(out, "  return {};", self.name(*value)).unwrap();
                } else {
                    writeln!(out, "  return;").unwrap();
                }
            }
            Terminator::Branch(target) => {
                self.emit_phi_assignments(func, *target, block, out, "  ");
                let id = target.into_raw();
                let label = func.blocks[*target].label.as_deref().unwrap_or("?");
                writeln!(out, "  goto block_{label}_{id};").unwrap();
            }
            Terminator::CondBranch(cond, then_block, else_block) => {
                let then_label = func.blocks[*then_block].label.as_deref().unwrap_or("?");
                let then_id = then_block.into_raw();
                let else_label = func.blocks[*else_block].label.as_deref().unwrap_or("?");
                let else_id = else_block.into_raw();
                let cond = self.name(*cond);
                if cond.starts_with('(') && cond.ends_with(')') {
                    writeln!(out, "  if {cond} {{").unwrap();
                } else {
                    writeln!(out, "  if ({cond}) {{").unwrap();
                }
                self.emit_phi_assignments(func, *then_block, block, out, "    ");
                writeln!(out, "    goto block_{then_label}_{then_id};").unwrap();
                writeln!(out, "  }} else {{").unwrap();
                self.emit_phi_assignments(func, *else_block, block, out, "    ");
                writeln!(out, "    goto block_{else_label}_{else_id};").unwrap();
                writeln!(out, "  }}").unwrap();
            }
            Terminator::Unreachable => writeln!(out, "  for (;;) {{}}").unwrap(),
        }
        Ok(())
    }

    fn predeclare_phi_vars(&mut self, func: &Function, out: &mut String) {
        for (_bid, block) in func.blocks.iter() {
            for (index, inst) in block.insts.iter().enumerate() {
                let InstKind::Phi(_) = &inst.kind else {
                    continue;
                };
                let ct = ctype_of(&inst.ty);
                if ct == "void" {
                    continue;
                }
                let v = block.value_at(index);
                let name = fresh_c(&mut self.counter, "phi");
                self.set(v, name.clone(), ct.clone());
                self.record_struct_type(v, &inst.ty);
                writeln!(out, "  {ct} {name}; // phi").unwrap();
            }
        }
    }

    fn emit_inst(&mut self, inst: &Inst, v: Value, out: &mut String) -> Result<(), String> {
        self.record_struct_type(v, &inst.ty);
        match &inst.kind {
            // ponytail: Const values always inlined — no variable emitted.
            InstKind::Const(value) => self.emit_const(inst, v, value),
            InstKind::HeapAlloc(_) => self.emit_heap_alloc(inst, v, out),
            InstKind::HeapFree(ptr) => self.emit_heap_free(*ptr, out),
            InstKind::Alloca(_) => self.emit_alloca(inst, v, out),
            InstKind::Store(value, ptr) => self.emit_store(*value, *ptr, out),
            InstKind::Load(ptr) => self.emit_load(inst, v, *ptr, out),
            InstKind::BinOp(op, lhs, rhs) => self.emit_binop(inst, v, *op, *lhs, *rhs, out),
            InstKind::UnOp(op, operand) => self.emit_unop(inst, v, *op, *operand, out),
            InstKind::Cmp(op, lhs, rhs) => self.emit_cmp(v, *op, *lhs, *rhs, out),
            InstKind::Cast(op, value, target) => {
                self.emit_cast(v, *op, *value, target, out);
            }
            InstKind::SizeOf(ty) => self.emit_size_of(inst, v, ty, out),

            InstKind::StructValue(fields) => self.emit_struct_value(inst, v, fields, out)?,
            InstKind::SparseStructValue(fields) => {
                self.emit_sparse_struct_value(inst, v, fields, out)?;
            }
            InstKind::ArrayValue(elements) => self.emit_array_value(inst, v, elements, out),
            InstKind::TupleValue(elements) => self.emit_tuple_value(inst, v, elements, out),

            InstKind::ExtractValue(aggregate, index) => {
                self.emit_extract_value(inst, v, *aggregate, *index, out)?;
            }
            InstKind::FieldPtr(base, index) => {
                self.emit_field_ptr(inst, v, *base, *index, out);
            }
            InstKind::IndexPtr(base, index) => {
                self.emit_index_ptr(inst, v, *base, *index, None, out);
            }
            InstKind::CheckedIndexPtr(base, index, len) => {
                self.emit_index_ptr(inst, v, *base, *index, Some(*len), out);
            }

            InstKind::Phi(_) => self.emit_phi(inst, v),
            InstKind::Call(callee, args) => self.emit_call(inst, v, callee, args, out)?,
            InstKind::FunctionRef(function) => self.emit_function_ref(inst, v, function)?,
            InstKind::CallIndirect(callee, args) => {
                self.emit_indirect_call(inst, v, *callee, args, out);
            }
        }
        Ok(())
    }

    fn emit_const(&mut self, inst: &Inst, value: Value, constant: &ConstValue) {
        let ct = ctype_of(&inst.ty);
        let expr = match constant {
            ConstValue::Int(value, _) => c_int_literal(*value, &inst.ty),
            ConstValue::NegativeInt(value, _) => c_negative_int_literal(*value, &inst.ty),
            ConstValue::Float(value, _) => format!("(({ct}){value})"),
            ConstValue::Bool(value) => value.to_string(),
            ConstValue::String(value) => {
                let (inner, len) = c_string_parts(value);
                if is_fat_repr(&inst.ty) {
                    format!("(riddle_str){{ \"{inner}\", {len} }}")
                } else {
                    format!("\"{inner}\"")
                }
            }
            ConstValue::Char(value) => format!("UINT32_C({})", u32::from(*value)),
            ConstValue::Unit => "((riddle_unit)0)".into(),
        };
        self.set_inline(value, expr, ct);
    }

    fn emit_heap_alloc(&mut self, inst: &Inst, value: Value, out: &mut String) {
        let ct = ctype_of(&inst.ty);
        let inner_ct = pointee_ct(&inst.ty);
        let name = fresh_c(&mut self.counter, "h");
        self.set(value, name.clone(), ct.clone());
        writeln!(
            out,
            "  {} {} = ({}){}(sizeof({}));",
            ct,
            name,
            ct,
            if self.no_gc {
                "riddle_alloc"
            } else {
                "rgc_alloc"
            },
            inner_ct
        )
        .unwrap();
    }

    fn emit_heap_free(&self, ptr: Value, out: &mut String) {
        writeln!(
            out,
            "  {}({});",
            if self.no_gc {
                "riddle_free"
            } else {
                "rgc_free"
            },
            self.name(ptr)
        )
        .unwrap();
    }

    fn emit_alloca(&mut self, inst: &Inst, value: Value, out: &mut String) {
        let inner = match &inst.ty {
            Type::Ptr(inner) | Type::Ref(inner, _) => inner.as_ref(),
            _ => &Type::Void,
        };
        let (decl_pre, decl_suf) = c_decl_parts(inner);
        let name = fresh_c(&mut self.counter, "a");
        let ct = format!("{decl_pre}{decl_suf}");
        self.set(value, name.clone(), ct);
        self.direct_storage.insert(value.0);
        writeln!(out, "  {decl_pre} {name}{decl_suf}; // stack").unwrap();
    }

    fn emit_store(&self, value: Value, ptr: Value, out: &mut String) {
        let value_name = self.value_expr(value);
        let ptr_name = self.name(ptr).to_owned();
        let ptr_ct = self.ctypes.get(ptr.0 as usize).map_or("", String::as_str);
        let value_ct = self.ctypes.get(value.0 as usize).map_or("", String::as_str);
        if ptr_ct.ends_with(']') {
            writeln!(out, "  memcpy({ptr_name}, {value_name}, sizeof({ptr_ct}));").unwrap();
        } else if value_ct.ends_with(']') {
            let destination = if self.is_indirect(ptr) {
                ptr_name
            } else {
                format!("&{ptr_name}")
            };
            writeln!(
                out,
                "  memcpy({destination}, {value_name}, sizeof({value_ct}));"
            )
            .unwrap();
        } else if self.is_indirect(ptr) {
            if let Some(inner) = strip_addr_of(&ptr_name) {
                writeln!(out, "  {inner} = {value_name};").unwrap();
            } else {
                writeln!(out, "  *{ptr_name} = {value_name};").unwrap();
            }
        } else {
            writeln!(out, "  {ptr_name} = {value_name};").unwrap();
        }
    }

    fn emit_load(&mut self, inst: &Inst, value: Value, ptr: Value, out: &mut String) {
        let name = fresh_c(&mut self.counter, "l");
        let ct = ctype_of(&inst.ty);
        if ct == "void" {
            self.set(value, String::new(), "void".into());
        } else if ct.ends_with(']') {
            let ptr_name = self.name(ptr).to_owned();
            let (decl_pre, decl_suf) = c_decl_parts(&inst.ty);
            let decl_ct = format!("{decl_pre}{decl_suf}");
            self.set(value, name.clone(), decl_ct);
            writeln!(out, "  {decl_pre} {name}{decl_suf};").unwrap();
            writeln!(out, "  memcpy({name}, {ptr_name}, sizeof({name}));").unwrap();
        } else {
            let ptr_name = self.name(ptr);
            let rhs = if self.is_indirect(ptr) {
                strip_addr_of(ptr_name).map_or_else(|| format!("*{ptr_name}"), ToOwned::to_owned)
            } else {
                ptr_name.to_owned()
            };
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {rhs};").unwrap();
        }
    }

    fn emit_binop(
        &mut self,
        inst: &Inst,
        value: Value,
        op: BinOp,
        lhs: Value,
        rhs: Value,
        out: &mut String,
    ) {
        let ct = ctype_of(&inst.ty);
        if ct == "void" {
            self.set(value, String::new(), "void".into());
            return;
        }
        let lhs_name = self.name(lhs).to_owned();
        let rhs_name = self.name(rhs).to_owned();
        let expr = match &inst.ty {
            Type::Int(ty) => integer_binop_expr(*ty, op, &lhs_name, &rhs_name),
            Type::Float(ty) => float_binop_expr(*ty, op, &lhs_name, &rhs_name),
            _ => format!("({} {} {})", lhs_name, binop_c(op), rhs_name),
        };
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "b");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
    }

    fn emit_unop(&mut self, inst: &Inst, value: Value, op: UnOp, operand: Value, out: &mut String) {
        let ct = ctype_of(&inst.ty);
        let operand_name = self.name(operand).to_owned();
        let operand_ct = self
            .ctypes
            .get(operand.0 as usize)
            .cloned()
            .unwrap_or_default();
        let is_noop_ref = matches!(op, UnOp::Ref | UnOp::MutRef)
            && (self.is_indirect(operand)
                || is_fat_repr(&inst.ty)
                || matches!(&inst.ty, Type::Ref(inner, _) if matches!(inner.as_ref(), Type::Array(..))));
        let is_noop_deref =
            matches!(op, UnOp::Deref) && operand_ct == "riddle_str" && ct == "riddle_str";
        let expr = if is_noop_ref || is_noop_deref {
            operand_name
        } else if matches!(op, UnOp::Neg | UnOp::Not) && matches!(&inst.ty, Type::Int(_)) {
            let Type::Int(ty) = &inst.ty else {
                unreachable!()
            };
            integer_unop_expr(*ty, op, &operand_name)
        } else {
            let op_str = match op {
                UnOp::Neg => "-",
                UnOp::Not if matches!(inst.ty, Type::Int(_)) => "~",
                UnOp::Not => "!",
                UnOp::Ref | UnOp::MutRef => "&",
                UnOp::Deref => "*",
            };
            format!("({op_str}{operand_name})")
        };
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 && !matches!(op, UnOp::Deref) {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "u");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
    }

    fn emit_cmp(&mut self, value: Value, op: CmpOp, lhs: Value, rhs: Value, out: &mut String) {
        let lhs_name = self.name(lhs).to_owned();
        let rhs_name = self.name(rhs).to_owned();
        let lhs_type = self.ctypes.get(lhs.0 as usize).map_or("", String::as_str);
        let expr = if lhs_type == "riddle_str" && matches!(op, CmpOp::Eq | CmpOp::Neq) {
            let equal = format!(
                "(({lhs_name}).len == ({rhs_name}).len && memcmp(({lhs_name}).ptr, ({rhs_name}).ptr, ({lhs_name}).len) == 0)"
            );
            if matches!(op, CmpOp::Neq) {
                format!("(!{equal})")
            } else {
                equal
            }
        } else {
            format!("({} {} {})", lhs_name, cmpop_c(op), rhs_name)
        };
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 {
            self.set_inline(value, expr, "bool".into());
        } else {
            let name = fresh_c(&mut self.counter, "cmp");
            self.set(value, name.clone(), "bool".into());
            writeln!(out, "  bool {name} = {expr};").unwrap();
        }
    }

    fn emit_cast(
        &mut self,
        value: Value,
        op: CastOp,
        source: Value,
        target: &Type,
        out: &mut String,
    ) {
        let ct = ctype_of(target);
        let source = self.value_expr(source);
        let expr = match (op, target) {
            (CastOp::IntToInt, Type::Int(ty)) => integer_cast_expr(*ty, &source),
            (CastOp::FloatToInt, Type::Int(ty)) => float_to_int_expr(*ty, &source),
            _ => format!("(({ct}){source})"),
        };
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "cast");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
    }

    fn emit_size_of(&mut self, inst: &Inst, value: Value, ty: &Type, out: &mut String) {
        let ct = ctype_of(&inst.ty);
        let name = fresh_c(&mut self.counter, "size");
        self.set(value, name.clone(), ct.clone());
        writeln!(out, "  {} {} = sizeof({});", ct, name, ctype_of(ty)).unwrap();
    }

    fn emit_struct_value(
        &mut self,
        inst: &Inst,
        value: Value,
        fields: &[Value],
        out: &mut String,
    ) -> Result<(), String> {
        let name = fresh_c(&mut self.counter, "s");
        let ct = ctype_of(&inst.ty);
        self.set(value, name.clone(), ct.clone());
        if is_fat_repr(&inst.ty) {
            let [ptr, len] = fields else {
                return Err("fat pointer requires a pointer and length".into());
            };
            let ptr_cast = if is_slice_ref(&inst.ty) {
                "void*"
            } else {
                "const char*"
            };
            writeln!(
                out,
                "  {} {} = {{ ({}){}, {} }};",
                ct,
                name,
                ptr_cast,
                self.name(*ptr),
                self.name(*len)
            )
            .unwrap();
        } else if let Type::Struct(strukt) = &inst.ty
            && strukt
                .fields
                .iter()
                .any(|(_, field_ty)| matches!(field_ty, Type::Array(_, _)))
        {
            writeln!(out, "  {ct} {name} = {{0}};").unwrap();
            for (index, value) in fields.iter().enumerate() {
                let Some((field_name, field_ty)) = strukt.fields.get(index) else {
                    continue;
                };
                let field = c_source_name('m', field_name);
                let value_name = self.name(*value);
                if matches!(field_ty, Type::Array(_, _)) {
                    writeln!(
                        out,
                        "  memcpy({name}.{field}, {value_name}, sizeof({name}.{field}));"
                    )
                    .unwrap();
                } else {
                    writeln!(out, "  {name}.{field} = {value_name};").unwrap();
                }
            }
        } else {
            let fields = fields
                .iter()
                .map(|field| self.name(*field).to_owned())
                .collect::<Vec<_>>();
            if fields.is_empty() {
                writeln!(out, "  {ct} {name} = {{0}};").unwrap();
            } else {
                writeln!(out, "  {} {} = {{ {} }};", ct, name, fields.join(", ")).unwrap();
            }
        }
        Ok(())
    }

    fn emit_sparse_struct_value(
        &mut self,
        inst: &Inst,
        value: Value,
        fields: &[(usize, Value)],
        out: &mut String,
    ) -> Result<(), String> {
        let name = fresh_c(&mut self.counter, "s");
        let ct = ctype_of(&inst.ty);
        self.set(value, name.clone(), ct.clone());
        writeln!(out, "  {ct} {name} = {{0}};").unwrap();
        let Type::Struct(strukt) = &inst.ty else {
            return Err("sparse aggregate initializer requires a struct type".into());
        };
        for (index, value) in fields {
            let Some((field_name, field_ty)) = strukt.fields.get(*index) else {
                return Err(format!("aggregate field index {index} is out of bounds"));
            };
            let field = c_source_name('m', field_name);
            let value_name = self.name(*value);
            if matches!(field_ty, Type::Array(_, _)) {
                writeln!(
                    out,
                    "  memcpy({name}.{field}, {value_name}, sizeof({name}.{field}));"
                )
                .unwrap();
            } else {
                writeln!(out, "  {name}.{field} = {value_name};").unwrap();
            }
        }
        Ok(())
    }

    fn emit_array_value(
        &mut self,
        inst: &Inst,
        value: Value,
        elements: &[Value],
        out: &mut String,
    ) {
        let name = fresh_c(&mut self.counter, "arr");
        let (decl_pre, decl_suf) = c_decl_parts(&inst.ty);
        self.set(value, name.clone(), format!("{decl_pre}{decl_suf}"));
        let nested =
            matches!(&inst.ty, Type::Array(inner, _) if matches!(inner.as_ref(), Type::Array(..)));
        if nested {
            writeln!(out, "  {decl_pre} {name}{decl_suf} = {{0}};").unwrap();
            for (index, element) in elements.iter().enumerate() {
                writeln!(
                    out,
                    "  memcpy({}[{}], {}, sizeof({}[{}]));",
                    name,
                    index,
                    self.name(*element),
                    name,
                    index
                )
                .unwrap();
            }
        } else {
            let values = elements
                .iter()
                .map(|element| self.name(*element).to_owned())
                .collect::<Vec<_>>();
            if values.is_empty() {
                writeln!(out, "  {decl_pre} {name}{decl_suf} = {{0}};").unwrap();
            } else {
                writeln!(
                    out,
                    "  {} {}{} = {{ {} }};",
                    decl_pre,
                    name,
                    decl_suf,
                    values.join(", ")
                )
                .unwrap();
            }
        }
    }

    fn emit_tuple_value(
        &mut self,
        inst: &Inst,
        value: Value,
        elements: &[Value],
        out: &mut String,
    ) {
        let name = fresh_c(&mut self.counter, "tup");
        let ct = ctype_of(&inst.ty);
        self.set(value, name.clone(), ct.clone());
        let elements = elements
            .iter()
            .map(|element| self.name(*element).to_owned())
            .collect::<Vec<_>>();
        writeln!(out, "  {} {} = {{ {} }};", ct, name, elements.join(", ")).unwrap();
    }

    fn emit_extract_value(
        &mut self,
        inst: &Inst,
        value: Value,
        aggregate: Value,
        index: usize,
        out: &mut String,
    ) -> Result<(), String> {
        let ct = ctype_of(&inst.ty);
        let base = self.name(aggregate).to_owned();
        let aggregate_ct = self
            .ctypes
            .get(aggregate.0 as usize)
            .map_or("", String::as_str);
        let field = if matches!(aggregate_ct, "riddle_str" | "riddle_slice") {
            match index {
                0 => "ptr".into(),
                1 => "len".into(),
                _ => return Err(format!("fat pointer field index {index} is out of bounds")),
            }
        } else {
            self.struct_types
                .get(&aggregate.0)
                .and_then(|strukt| strukt.fields.get(index))
                .map_or_else(
                    || c_source_name('m', &format!("f{index}")),
                    |(name, _)| c_source_name('m', name),
                )
        };
        let mut expr = field_expr(&base, &field, self.is_indirect(aggregate));
        if aggregate_ct == "riddle_slice" && index == 0 {
            expr = format!("(({ct}){expr})");
        }
        if matches!(&inst.ty, Type::Array(..)) && self.is_indirect(aggregate) {
            let name = fresh_c(&mut self.counter, "ev");
            let (decl_pre, decl_suf) = c_decl_parts(&inst.ty);
            self.set(value, name.clone(), ct);
            writeln!(out, "  {decl_pre} {name}{decl_suf};").unwrap();
            writeln!(out, "  memcpy({name}, {expr}, sizeof({name}));").unwrap();
        } else if !self.is_indirect(aggregate)
            && self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1
        {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "ev");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
        Ok(())
    }

    fn emit_field_ptr(
        &mut self,
        inst: &Inst,
        value: Value,
        base: Value,
        index: usize,
        out: &mut String,
    ) {
        let ct = ctype_of(&inst.ty);
        let base_name = self.name(base).to_owned();
        let (field, field_ty) = self
            .struct_types
            .get(&base.0)
            .and_then(|strukt| strukt.fields.get(index))
            .map_or_else(
                || (c_source_name('m', &format!("f{index}")), None),
                |(name, ty)| (c_source_name('m', name), Some(ty)),
            );
        let mut field = field_expr(&base_name, &field, self.is_indirect(base));
        let mut ty = field_ty;
        while let Some(Type::Array(inner, _)) = ty {
            field.push_str("[0]");
            ty = Some(inner);
        }
        let expr = format!("(&{field})");
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "fp");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
    }

    fn emit_index_ptr(
        &mut self,
        inst: &Inst,
        value: Value,
        base: Value,
        index: Value,
        checked_len: Option<Value>,
        out: &mut String,
    ) {
        let ct = ctype_of(&inst.ty);
        let base_name = self.name(base).to_owned();
        let base_ct = self.ctypes.get(base.0 as usize).map_or("", String::as_str);
        let index_name = self.name(index).to_owned();
        if let Some(len) = checked_len {
            writeln!(
                out,
                "  if ((size_t){} >= (size_t){}) {{ fputs(\"riddle: index out of bounds\\n\", stderr); abort(); }}",
                index_name,
                self.name(len)
            )
            .unwrap();
        }
        let element = match &inst.ty {
            Type::Ptr(element) | Type::Ref(element, _) => element.as_ref(),
            _ => &Type::Unit,
        };
        let expr = if base_ct == "riddle_slice" {
            format!(
                "(&(({}*){}.ptr)[{}])",
                ctype_of(element),
                base_name,
                index_name
            )
        } else if !self.is_indirect(base) && matches!(element, Type::Array(..)) {
            format!("({base_name}[{index_name}])")
        } else {
            let stride = array_leaf_count(element);
            let index = if stride == 1 {
                index_name
            } else {
                format!("(({index_name}) * {stride})")
            };
            format!("(&{base_name}[{index}])")
        };
        if self.use_counts.get(&value.0).copied().unwrap_or(0) <= 1 {
            self.set_inline(value, expr, ct);
        } else {
            let name = fresh_c(&mut self.counter, "ip");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {expr};").unwrap();
        }
    }

    fn emit_phi(&mut self, inst: &Inst, value: Value) {
        if ctype_of(&inst.ty) == "void" {
            self.set(value, String::new(), "void".into());
        }
    }

    fn emit_call(
        &mut self,
        inst: &Inst,
        value: Value,
        callee: &FuncRef,
        args: &[Value],
        out: &mut String,
    ) -> Result<(), String> {
        let ct = ctype_of(&inst.ty);
        let callee_name = match callee {
            FuncRef::Local(name) => self.c_function_name(name)?,
            FuncRef::Intrinsic(name) => name.clone(),
            FuncRef::Extern(name) => self.extern_name(name)?.to_owned(),
        };
        let is_extern = matches!(callee, FuncRef::Extern(_));
        // For extern calls, expand &str arguments into (ptr, len) pairs to
        // match the expanded C parameter list.
        let mut arg_strs = Vec::new();
        for arg in args {
            let name = self.name(*arg).to_owned();
            let arg_ct = self.ctypes.get(arg.0 as usize).map_or("", String::as_str);
            if is_extern && arg_ct == "riddle_str" {
                let deref = if self.is_indirect(*arg) {
                    "->"
                } else {
                    "."
                };
                arg_strs.push(format!("{name}{deref}ptr"));
                arg_strs.push(format!("{name}{deref}len"));
            } else {
                arg_strs.push(name);
            }
        }
        let args = arg_strs.join(", ");
        if matches!(&inst.ty, Type::Unit) {
            writeln!(out, "  {callee_name}({args});").unwrap();
            self.set_inline(value, "((riddle_unit)0)".into(), "riddle_unit".into());
        } else if matches!(&inst.ty, Type::Never | Type::Void) {
            writeln!(out, "  {callee_name}({args});").unwrap();
            self.set(value, String::new(), "void".into());
        } else if is_extern && is_fat_repr(&inst.ty) {
            let ffi_name = fresh_c(&mut self.counter, "ffi_str");
            let name = fresh_c(&mut self.counter, "call");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  const char* {ffi_name} = {callee_name}({args});").unwrap();
            writeln!(
                out,
                "  {ct} {name} = (riddle_str){{ {ffi_name}, {ffi_name} ? strlen({ffi_name}) : 0 }};"
            )
            .unwrap();
        } else {
            let name = fresh_c(&mut self.counter, "call");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {callee_name}({args});").unwrap();
        }
        Ok(())
    }

    fn emit_function_ref(
        &mut self,
        inst: &Inst,
        value: Value,
        function: &FuncRef,
    ) -> Result<(), String> {
        let name = match function {
            FuncRef::Local(name) => self.c_function_name(name)?,
            FuncRef::Intrinsic(name) => name.clone(),
            FuncRef::Extern(name) => self.extern_name(name)?.to_owned(),
        };
        self.set_inline(value, name, ctype_of(&inst.ty));
        Ok(())
    }

    fn emit_indirect_call(
        &mut self,
        inst: &Inst,
        value: Value,
        callee: Value,
        args: &[Value],
        out: &mut String,
    ) {
        let ct = ctype_of(&inst.ty);
        let callee = self.name(callee).to_owned();
        let args = args
            .iter()
            .map(|arg| self.name(*arg).to_owned())
            .collect::<Vec<_>>()
            .join(", ");
        if matches!(&inst.ty, Type::Unit) {
            writeln!(out, "  {callee}({args});").unwrap();
            self.set_inline(value, "((riddle_unit)0)".into(), "riddle_unit".into());
        } else if matches!(&inst.ty, Type::Never | Type::Void) {
            writeln!(out, "  {callee}({args});").unwrap();
            self.set(value, String::new(), "void".into());
        } else {
            let name = fresh_c(&mut self.counter, "call");
            self.set(value, name.clone(), ct.clone());
            writeln!(out, "  {ct} {name} = {callee}({args});").unwrap();
        }
    }

    fn emit_phi_assignments(
        &self,
        func: &Function,
        target: crate::value::BlockId,
        from: crate::value::BlockId,
        out: &mut String,
        indent: &str,
    ) {
        let block = &func.blocks[target];
        for (index, inst) in block.insts.iter().enumerate() {
            let InstKind::Phi(pairs) = &inst.kind else {
                continue;
            };
            if ctype_of(&inst.ty) == "void" {
                continue;
            }
            let Some((incoming, _)) = pairs.iter().find(|(_, pred)| *pred == from) else {
                continue;
            };
            let phi_value = block.value_at(index);
            writeln!(
                out,
                "{}{} = {};",
                indent,
                self.name(phi_value),
                self.name(*incoming)
            )
            .unwrap();
        }
    }

    fn c_function_name(&self, name: &str) -> Result<String, String> {
        if self.needs_runtime && name == "main" {
            return Ok(c_source_name('f', name));
        }
        if !self.c_exports.contains(name) {
            return Ok(c_function_name(name));
        }
        if is_valid_c_extern_name(name) {
            Ok(name.into())
        } else {
            Err(format!(
                "C export function `{name}` is not a valid C identifier"
            ))
        }
    }
}

/// Collect unique struct types from all instructions across the module.
fn collect_structs(module: &Module) -> Vec<StructType> {
    let mut seen: HashMap<String, StructType> = HashMap::new();
    for &fid in &module.function_order {
        let func = &module.functions[fid];
        collect_struct_type(&func.ret_type, &mut seen);
        for param in &func.params {
            collect_struct_type(&param.ty, &mut seen);
        }
        for (_bid, block) in func.blocks.iter() {
            for inst in &block.insts {
                collect_struct_type(&inst.ty, &mut seen);
                if let InstKind::SizeOf(ty) = &inst.kind {
                    collect_struct_type(ty, &mut seen);
                }
            }
        }
    }
    for external in &module.externs {
        collect_struct_type(&external.ret_type, &mut seen);
        for param in &external.params {
            collect_struct_type(param, &mut seen);
        }
    }
    let mut out: Vec<StructType> = seen.into_values().collect();
    out.sort_by(|a, b| {
        struct_depth(a)
            .cmp(&struct_depth(b))
            .then_with(|| a.name.cmp(&b.name))
    });
    out
}

fn collect_fn_ptrs(module: &Module) -> Vec<FnPtrType> {
    let mut seen = HashSet::new();
    for &fid in &module.function_order {
        let function = &module.functions[fid];
        collect_fn_ptr_type(&function.ret_type, &mut seen);
        for param in &function.params {
            collect_fn_ptr_type(&param.ty, &mut seen);
        }
        for (_, block) in function.blocks.iter() {
            for inst in &block.insts {
                collect_fn_ptr_type(&inst.ty, &mut seen);
                if let InstKind::SizeOf(ty) = &inst.kind {
                    collect_fn_ptr_type(ty, &mut seen);
                }
            }
        }
    }
    for external in &module.externs {
        collect_fn_ptr_type(&external.ret_type, &mut seen);
        for param in &external.params {
            collect_fn_ptr_type(param, &mut seen);
        }
    }
    let mut signatures = seen.into_iter().collect::<Vec<_>>();
    signatures.sort_by_key(fn_ptr_name);
    signatures
}

fn collect_fn_ptr_type(ty: &Type, seen: &mut HashSet<FnPtrType>) {
    match ty {
        Type::FnPtr(signature) => {
            if seen.insert(signature.clone()) {
                for param in &signature.params {
                    collect_fn_ptr_type(param, seen);
                }
                collect_fn_ptr_type(&signature.ret, seen);
            }
        }
        Type::Struct(strukt) => {
            for (_, field) in &strukt.fields {
                collect_fn_ptr_type(field, seen);
            }
        }
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) | Type::Slice(inner) => {
            collect_fn_ptr_type(inner, seen);
        }
        Type::Tuple(elements) => {
            for element in elements {
                collect_fn_ptr_type(element, seen);
            }
        }
        _ => {}
    }
}

fn module_has_heap_alloc(module: &Module) -> bool {
    module.function_order.iter().any(|fid| {
        module.functions[*fid].blocks.iter().any(|(_, block)| {
            block
                .insts
                .iter()
                .any(|inst| matches!(inst.kind, InstKind::HeapAlloc(_)))
        })
    })
}

/// Whether any emitted function calls into the GC runtime (`rgc_*` externs),
/// e.g. `Vector` growing its buffer through `rgc_realloc`.
fn module_calls_runtime(module: &Module) -> bool {
    module.function_order.iter().any(|fid| {
        module.functions[*fid].blocks.iter().any(|(_, block)| {
            block.insts.iter().any(|inst| {
                matches!(
                    &inst.kind,
                    InstKind::Call(FuncRef::Extern(name), _) if name.starts_with("rgc_")
                )
            })
        })
    })
}

fn collect_struct_type(ty: &Type, seen: &mut HashMap<String, StructType>) {
    match ty {
        Type::Struct(st) => {
            if seen.insert(st.name.clone(), st.clone()).is_some() {
                return;
            }
            for (_, field_ty) in &st.fields {
                collect_struct_type(field_ty, seen);
            }
        }
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) | Type::Slice(inner) => {
            collect_struct_type(inner, seen);
        }
        Type::Tuple(elements) => {
            let tuple = tuple_struct_type(elements);
            if seen.insert(tuple.name.clone(), tuple).is_some() {
                return;
            }
            for element in elements {
                collect_struct_type(element, seen);
            }
        }
        Type::FnPtr(signature) => {
            for param in &signature.params {
                collect_struct_type(param, seen);
            }
            collect_struct_type(&signature.ret, seen);
        }
        _ => {}
    }
}

fn struct_depth(st: &StructType) -> usize {
    1 + st
        .fields
        .iter()
        .map(|(_, ty)| type_struct_depth(ty))
        .max()
        .unwrap_or(0)
}

fn type_struct_depth(ty: &Type) -> usize {
    match ty {
        Type::Struct(st) => struct_depth(st),
        Type::Ptr(inner) | Type::Ref(inner, _) | Type::Array(inner, _) | Type::Slice(inner) => {
            type_struct_depth(inner)
        }
        Type::Tuple(elements) => struct_depth(&tuple_struct_type(elements)),
        _ => 0,
    }
}

/// Count how many times each value is referenced as an operand.
fn count_uses(func: &Function) -> HashMap<u32, u32> {
    let mut uses: HashMap<u32, u32> = HashMap::new();
    for (_bid, block) in func.blocks.iter() {
        for inst in &block.insts {
            for v in inst_operands(inst) {
                *uses.entry(v.0).or_insert(0) += 1;
            }
        }
        match &block.terminator {
            Terminator::Return(Some(v)) => {
                *uses.entry(v.0).or_insert(0) += 1;
            }
            Terminator::CondBranch(cond, _, _) => {
                *uses.entry(cond.0).or_insert(0) += 1;
            }
            _ => {}
        }
    }
    uses
}

/// Collect all Value operands referenced by an instruction.
fn inst_operands(inst: &Inst) -> Vec<Value> {
    match &inst.kind {
        InstKind::Store(value, ptr) => vec![*value, *ptr],
        InstKind::Load(value)
        | InstKind::UnOp(_, value)
        | InstKind::Cast(_, value, _)
        | InstKind::ExtractValue(value, _)
        | InstKind::FieldPtr(value, _)
        | InstKind::HeapFree(value) => vec![*value],
        InstKind::BinOp(_, lhs, rhs) | InstKind::Cmp(_, lhs, rhs) => vec![*lhs, *rhs],
        InstKind::StructValue(fields) => fields.clone(),
        InstKind::SparseStructValue(fields) => fields.iter().map(|(_, value)| *value).collect(),
        InstKind::ArrayValue(elements) | InstKind::TupleValue(elements) => elements.clone(),
        InstKind::IndexPtr(base, index) => vec![*base, *index],
        InstKind::CheckedIndexPtr(base, index, len) => vec![*base, *index, *len],
        InstKind::Phi(pairs) => pairs.iter().map(|(v, _)| *v).collect(),
        InstKind::Call(_, args) => args.clone(),
        InstKind::CallIndirect(callee, args) => {
            let mut values = vec![*callee];
            values.extend(args);
            values
        }
        _ => vec![], // Const, HeapAlloc, Alloca, SizeOf: no operands
    }
}

fn fresh_c(ctr: &mut u64, prefix: &str) -> String {
    *ctr += 1;
    format!("{prefix}{ctr}")
}

fn c_return_type(func: &Function) -> String {
    if func.name == "main" && matches!(func.ret_type, Type::Unit) {
        "int".into()
    } else {
        c_callable_return_type(&func.ret_type)
    }
}

fn c_callable_return_type(ty: &Type) -> String {
    if matches!(ty, Type::Unit | Type::Never | Type::Void) {
        "void".into()
    } else {
        ctype_of(ty)
    }
}

fn ctype_of(ty: &Type) -> String {
    match ty {
        Type::Int(ity) => match ity {
            IntTy::I8 => "int8_t".into(),
            IntTy::I16 => "int16_t".into(),
            IntTy::I32 => "int32_t".into(),
            IntTy::I64 => "int64_t".into(),
            IntTy::Isize => "ptrdiff_t".into(),
            IntTy::U8 => "uint8_t".into(),
            IntTy::U16 => "uint16_t".into(),
            IntTy::U32 => "uint32_t".into(),
            IntTy::U64 => "uint64_t".into(),
            IntTy::Usize => "size_t".into(),
        },
        Type::Float(fty) => match fty {
            FloatTy::F32 => "float".into(),
            FloatTy::F64 => "double".into(),
        },
        Type::Bool => "bool".into(),
        Type::Char => "uint32_t".into(),
        Type::Str => "riddle_str".into(),
        Type::Slice(_) => "riddle_slice".into(),
        Type::Ptr(inner) => pointer_ctype(inner),
        Type::Ref(inner, _) => match inner.as_ref() {
            Type::Str => "riddle_str".into(),
            Type::Slice(_) => "riddle_slice".into(),
            _ => pointer_ctype(inner),
        },
        Type::Struct(s) => c_type_name(&s.name),
        Type::Array(..) => {
            let (prefix, suffix) = c_decl_parts(ty);
            format!("{prefix}{suffix}")
        }
        Type::Tuple(elements) => c_type_name(&tuple_name(elements)),
        Type::Enum(e) => c_type_name(&format!("enum::{}", e.name)),
        Type::FnPtr(signature) => fn_ptr_name(signature),
        Type::Unit => "riddle_unit".into(),
        Type::Never | Type::Void => "void".into(),
    }
}

fn c_int_literal(value: u64, ty: &Type) -> String {
    let ctype = ctype_of(ty);
    match ty {
        Type::Int(IntTy::U8 | IntTy::U16 | IntTy::U32 | IntTy::U64 | IntTy::Usize) => {
            format!("(({ctype})UINT64_C({value}))")
        }
        _ => format!("(({ctype}){value})"),
    }
}

fn c_negative_int_literal(magnitude: u64, ty: &Type) -> String {
    let minimum = match ty {
        Type::Int(IntTy::I8) if magnitude == 1 << 7 => Some("INT8_MIN"),
        Type::Int(IntTy::I16) if magnitude == 1 << 15 => Some("INT16_MIN"),
        Type::Int(IntTy::I32) if magnitude == 1 << 31 => Some("INT32_MIN"),
        Type::Int(IntTy::I64) if magnitude == 1 << 63 => Some("INT64_MIN"),
        Type::Int(IntTy::Isize) if magnitude == 1 << (usize::BITS - 1) => Some("PTRDIFF_MIN"),
        _ => None,
    };
    minimum.map_or_else(
        || {
            let ctype = ctype_of(ty);
            format!("(({ctype})-INT64_C({magnitude}))")
        },
        str::to_owned,
    )
}

fn pointer_ctype(inner: &Type) -> String {
    let mut pointee = inner;
    while let Type::Array(element, _) = pointee {
        pointee = element;
    }
    format!("{}*", ctype_of(pointee))
}

fn tuple_struct_type(elements: &[Type]) -> StructType {
    StructType {
        name: tuple_name(elements),
        fields: elements
            .iter()
            .enumerate()
            .map(|(index, ty)| (format!("f{index}"), ty.clone()))
            .collect(),
    }
}

fn tuple_name(elements: &[Type]) -> String {
    let mut hasher = DefaultHasher::new();
    elements.hash(&mut hasher);
    format!("riddle_tuple_{:016x}", hasher.finish())
}

fn array_leaf_count(ty: &Type) -> usize {
    match ty {
        Type::Array(inner, len) => len.saturating_mul(array_leaf_count(inner)),
        _ => 1,
    }
}

fn fn_ptr_name(signature: &FnPtrType) -> String {
    let mut hasher = DefaultHasher::new();
    signature.hash(&mut hasher);
    format!("riddle_fn_{:016x}", hasher.finish())
}

/// C type for FFI declarations — `&str` maps to plain `const char*` because C
/// functions expect C strings, not the fat pointer struct.
fn ctype_of_ffi(ty: &Type) -> String {
    match ty {
        Type::Ref(inner, _) if matches!(inner.as_ref(), Type::Str) => "const char*".into(),
        // C allocation APIs use `void*`; Riddle keeps the pointee type in the
        // MIR and inserts the compatible pointer conversion at call sites.
        Type::Ptr(_) => "void*".into(),
        _ => ctype_of(ty),
    }
}

fn c_ffi_return_type(ty: &Type) -> String {
    if matches!(ty, Type::Unit | Type::Never | Type::Void) {
        "void".into()
    } else {
        ctype_of_ffi(ty)
    }
}

/// Whether this type is represented as a fat pointer (struct) in C.
fn is_fat_repr(ty: &Type) -> bool {
    match ty {
        Type::Str => true,
        Type::Ref(inner, _) => !inner.is_sized(),
        _ => false,
    }
}

fn is_slice_ref(ty: &Type) -> bool {
    match ty {
        Type::Slice(_) => true,
        Type::Ref(inner, _) => matches!(inner.as_ref(), Type::Slice(_)),
        _ => false,
    }
}

/// Whether this type is `&str` (a reference to str). When passed to C extern
/// functions this must be expanded into two parameters: `const char*` and
/// `size_t`, because Riddle's `&str` is a fat pointer but C only sees the
/// raw pointer unless we explicitly pass the length.
fn is_str_ref(ty: &Type) -> bool {
    matches!(ty, Type::Ref(inner, _) if matches!(inner.as_ref(), Type::Str))
}

fn c_string_parts(value: &str) -> (String, usize) {
    if let Some(body) = raw_string_body(value) {
        return (escape_c_string(body), body.len());
    }

    let inner = if value.len() >= 2 {
        &value[1..value.len() - 1]
    } else {
        value
    };
    let decoded = decode_string(inner);
    (escape_c_string(&decoded), decoded.len())
}

fn decode_string(text: &str) -> String {
    let mut out = String::new();
    let mut chars = text.chars();
    while let Some(ch) = chars.next() {
        if ch != '\\' {
            out.push(ch);
            continue;
        }
        out.push(match chars.next() {
            Some('n') => '\n',
            Some('r') => '\r',
            Some('t') => '\t',
            Some('0') => '\0',
            Some(ch) => ch,
            None => '\\',
        });
    }
    out
}

fn raw_string_body(text: &str) -> Option<&str> {
    let rest = text.strip_prefix('r')?;
    let hashes = rest.bytes().take_while(|&b| b == b'#').count();
    let open_quote = 1 + hashes;
    if text.as_bytes().get(open_quote) != Some(&b'"') {
        return None;
    }

    let suffix_len = 1 + hashes;
    let suffix_start = text.len().checked_sub(suffix_len)?;
    if suffix_start <= open_quote || text.as_bytes().get(suffix_start) != Some(&b'"') {
        return None;
    }
    if !text.as_bytes()[suffix_start + 1..]
        .iter()
        .all(|&b| b == b'#')
    {
        return None;
    }

    Some(&text[open_quote + 1..suffix_start])
}

fn escape_c_string(text: &str) -> String {
    let mut out = String::new();
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\000"),
            _ => out.push(ch),
        }
    }
    out
}

fn struct_type_for_field_base(ty: &Type) -> Option<StructType> {
    match ty {
        Type::Struct(st) => Some(st.clone()),
        Type::Tuple(elements) => Some(tuple_struct_type(elements)),
        Type::Ptr(inner) | Type::Ref(inner, _) => struct_type_for_field_base(inner),
        _ => None,
    }
}

fn field_expr(base: &str, field: &str, indirect: bool) -> String {
    if indirect {
        format!("{base}->{field}")
    } else {
        format!("{base}.{field}")
    }
}

fn pointee_ct(ty: &Type) -> String {
    match ty {
        Type::Ptr(inner) | Type::Ref(inner, _) => ctype_of(inner),
        _ => "void".into(),
    }
}

/// Split a MIR type into C declaration parts: (prefix, `suffix_after_var_name`).
/// e.g. Array(Array(Foo, 3), 4) → ("Foo", "[4][3]")
fn c_decl_parts(ty: &Type) -> (String, String) {
    match ty {
        Type::Array(inner, len) => {
            let (pre, suf) = c_decl_parts(inner);
            (pre, format!("[{}]{}", (*len).max(1), suf))
        }
        _ => (ctype_of(ty), String::new()),
    }
}

fn c_param_decl(ty: &Type, name: &str) -> String {
    let (pre, suf) = c_decl_parts(ty);
    format!("{pre} {name}{suf}")
}

fn c_function_param_decl(func: &Function, ty: &Type, name: &str) -> String {
    if func.uses_c_string_abi && matches!(ty, Type::Ref(inner, _) if **inner == Type::Str) {
        format!("const char *{name}")
    } else {
        c_param_decl(ty, name)
    }
}

fn integer_binop_expr(ty: IntTy, op: BinOp, lhs: &str, rhs: &str) -> String {
    let target = ctype_of(&Type::Int(ty));
    let carrier = int_carrier_ctype(ty);
    let lhs_bits = format!("({carrier})({lhs})");
    let rhs_bits = format!("({carrier})({rhs})");

    match op {
        BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::BitAnd | BinOp::BitOr | BinOp::BitXor => {
            let raw = format!("(({}) {} {})", lhs_bits, binop_c(op), rhs_bits);
            if ty.is_signed() {
                int_from_bits_expr(ty, &raw)
            } else {
                format!("(({target}){raw})")
            }
        }
        BinOp::Div | BinOp::Mod => {
            let zero_guard = format!("({rhs} == ({target})0)");
            let op_type = if ty.is_signed() {
                target.clone()
            } else {
                carrier.to_owned()
            };
            let operation = format!(
                "(({})({}) {} ({})({}))",
                op_type,
                lhs,
                binop_c(op),
                op_type,
                rhs
            );
            let message = if matches!(op, BinOp::Div) {
                "division by zero"
            } else {
                "remainder by zero"
            };
            let zero_trap =
                format!("(fputs(\"riddle: {message}\\n\", stderr), abort(), ({target})0)");
            if ty.is_signed() {
                let overflow_guard = format!(
                    "(({}) == {} && ({}) == ({})-1)",
                    lhs,
                    int_min_const(ty),
                    rhs,
                    target
                );
                let overflow_message = if matches!(op, BinOp::Div) {
                    "integer division overflow"
                } else {
                    "integer remainder overflow"
                };
                let overflow_trap = format!(
                    "(fputs(\"riddle: {overflow_message}\\n\", stderr), abort(), ({target})0)"
                );
                format!(
                    "(({zero_guard}) ? {zero_trap} : (({overflow_guard}) ? {overflow_trap} : {operation}))"
                )
            } else {
                format!("(({zero_guard}) ? {zero_trap} : {operation})")
            }
        }
        BinOp::Shl | BinOp::Shr => {
            let count = format!(
                "((unsigned)({})({}) % {})",
                carrier,
                rhs,
                int_width_expr(ty)
            );
            let raw = match op {
                BinOp::Shl => format!("({lhs_bits} << {count})"),
                BinOp::Shr if ty.is_signed() => {
                    let complement = format!("~({lhs_bits})");
                    let shifted = format!("({complement} >> {count})");
                    let negative = int_from_bits_expr(ty, &format!("~{shifted}"));
                    let positive = int_from_bits_expr(ty, &format!("({lhs_bits} >> {count})"));
                    return format!("(({lhs}) >= 0 ? {positive} : {negative})");
                }
                BinOp::Shr => format!("({lhs_bits} >> {count})"),
                _ => unreachable!(),
            };
            if ty.is_signed() {
                int_from_bits_expr(ty, &raw)
            } else {
                format!("(({target}){raw})")
            }
        }
    }
}

fn float_binop_expr(ty: FloatTy, op: BinOp, lhs: &str, rhs: &str) -> String {
    if op == BinOp::Mod {
        let function = match ty {
            FloatTy::F32 => "fmodf",
            FloatTy::F64 => "fmod",
        };
        return format!("{function}({lhs}, {rhs})");
    }
    format!("({} {} {})", lhs, binop_c(op), rhs)
}

fn integer_unop_expr(ty: IntTy, op: UnOp, operand: &str) -> String {
    let target = ctype_of(&Type::Int(ty));
    let carrier = int_carrier_ctype(ty);
    let raw = match op {
        UnOp::Neg => format!("(({carrier})0 - ({carrier})({operand}))"),
        UnOp::Not => format!("~({carrier})({operand})"),
        _ => return format!("({}{})", unop_c(op), operand),
    };
    if ty.is_signed() {
        int_from_bits_expr(ty, &raw)
    } else {
        format!("(({target}){raw})")
    }
}

fn integer_cast_expr(ty: IntTy, src: &str) -> String {
    let target = ctype_of(&Type::Int(ty));
    if ty.is_signed() {
        int_from_bits_expr(ty, &format!("({})({})", int_unsigned_ctype(ty), src))
    } else {
        format!("(({target}){src})")
    }
}

fn float_to_int_expr(ty: IntTy, src: &str) -> String {
    let target = ctype_of(&Type::Int(ty));
    let source = format!("((long double)({src}))");
    let min = int_min_const(ty);
    let max = int_max_const(ty);
    format!(
        "(isnan({source}) ? ({target})0 : ({source} <= (long double)({min}) ? ({target})({min}) : ({source} >= (long double)({max}) ? ({target})({max}) : ({target})({src}))))"
    )
}

const fn int_carrier_ctype(ty: IntTy) -> &'static str {
    match ty {
        IntTy::I8 | IntTy::I16 | IntTy::I32 | IntTy::U8 | IntTy::U16 | IntTy::U32 => "uint32_t",
        IntTy::I64 | IntTy::U64 => "uint64_t",
        IntTy::Isize | IntTy::Usize => "uintptr_t",
    }
}

const fn int_unsigned_ctype(ty: IntTy) -> &'static str {
    match ty {
        IntTy::I8 | IntTy::U8 => "uint8_t",
        IntTy::I16 | IntTy::U16 => "uint16_t",
        IntTy::I32 | IntTy::U32 => "uint32_t",
        IntTy::I64 | IntTy::U64 => "uint64_t",
        IntTy::Isize | IntTy::Usize => "uintptr_t",
    }
}

const fn int_width_expr(ty: IntTy) -> &'static str {
    match ty {
        IntTy::I8 | IntTy::U8 => "8",
        IntTy::I16 | IntTy::U16 => "16",
        IntTy::I32 | IntTy::U32 => "32",
        IntTy::I64 | IntTy::U64 => "64",
        IntTy::Isize | IntTy::Usize => "(sizeof(uintptr_t) * CHAR_BIT)",
    }
}

fn int_from_bits_expr(ty: IntTy, bits: &str) -> String {
    let name = match ty {
        IntTy::I8 => "RIDDLE_I8_FROM_BITS",
        IntTy::I16 => "RIDDLE_I16_FROM_BITS",
        IntTy::I32 => "RIDDLE_I32_FROM_BITS",
        IntTy::I64 => "RIDDLE_I64_FROM_BITS",
        IntTy::Isize => "RIDDLE_ISIZE_FROM_BITS",
        IntTy::U8 | IntTy::U16 | IntTy::U32 | IntTy::U64 | IntTy::Usize => unreachable!(),
    };
    format!("{name}({bits})")
}

const fn int_min_const(ty: IntTy) -> &'static str {
    match ty {
        IntTy::I8 => "INT8_MIN",
        IntTy::I16 => "INT16_MIN",
        IntTy::I32 => "INT32_MIN",
        IntTy::I64 => "INT64_MIN",
        IntTy::Isize => "PTRDIFF_MIN",
        IntTy::U8 | IntTy::U16 | IntTy::U32 | IntTy::U64 | IntTy::Usize => "0",
    }
}

const fn int_max_const(ty: IntTy) -> &'static str {
    match ty {
        IntTy::I8 => "INT8_MAX",
        IntTy::I16 => "INT16_MAX",
        IntTy::I32 => "INT32_MAX",
        IntTy::I64 => "INT64_MAX",
        IntTy::Isize => "PTRDIFF_MAX",
        IntTy::U8 => "UINT8_MAX",
        IntTy::U16 => "UINT16_MAX",
        IntTy::U32 => "UINT32_MAX",
        IntTy::U64 => "UINT64_MAX",
        IntTy::Usize => "SIZE_MAX",
    }
}

const fn unop_c(op: UnOp) -> &'static str {
    match op {
        UnOp::Neg => "-",
        UnOp::Not => "~",
        UnOp::Ref | UnOp::MutRef => "&",
        UnOp::Deref => "*",
    }
}

const fn binop_c(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
    }
}

const fn cmpop_c(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Neq => "!=",
        CmpOp::Lt => "<",
        CmpOp::Gt => ">",
        CmpOp::LtEq => "<=",
        CmpOp::GtEq => ">=",
    }
}

/// If expr is `(&inner)`, return `inner`. Ponytail: cancel *& from inlined FieldPtr/IndexPtr.
fn strip_addr_of(expr: &str) -> Option<&str> {
    if expr.starts_with("(&") && expr.ends_with(')') {
        Some(&expr[2..expr.len() - 1])
    } else {
        None
    }
}

fn c_function_name(name: &str) -> String {
    if name == "main" {
        name.into()
    } else {
        c_source_name('f', name)
    }
}

fn c_type_name(name: &str) -> String {
    c_source_name('t', name)
}

fn c_source_name(kind: char, name: &str) -> String {
    let mut encoded = String::with_capacity(10 + name.len() * 2);
    write!(encoded, "riddle_{kind}_").unwrap();
    for byte in name.bytes() {
        write!(encoded, "{byte:02x}").unwrap();
    }
    encoded
}

fn is_valid_c_extern_name(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|ch| ch == '_' || ch.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        && !matches!(
            name,
            "auto"
                | "break"
                | "case"
                | "char"
                | "const"
                | "continue"
                | "default"
                | "do"
                | "double"
                | "else"
                | "enum"
                | "extern"
                | "float"
                | "for"
                | "goto"
                | "if"
                | "inline"
                | "int"
                | "long"
                | "register"
                | "restrict"
                | "return"
                | "short"
                | "signed"
                | "sizeof"
                | "static"
                | "struct"
                | "switch"
                | "typedef"
                | "union"
                | "unsigned"
                | "void"
                | "volatile"
                | "while"
                | "_Alignas"
                | "_Alignof"
                | "_Atomic"
                | "_Bool"
                | "_Complex"
                | "_Generic"
                | "_Imaginary"
                | "_Noreturn"
                | "_Static_assert"
                | "_Thread_local"
        )
}
